### ISSUE TITLE
This is what I wanna ask you.

### ISSUE THREAD

**Issue by DevStarKKK** [DevStarKKK/First-one#3]
Plz let me know how to install node_module.

**Comment by DevCreator0705** [comment]
It is very easy.
1)open command prompt
2)then npm install --g yarn
3)then yarn install
That's all for now.

**Comment by DevCreator0705** [comment]
Or you can try this.
1)open command prompt
2)then npm install
That's all for now.

**Comment by DevStarKKK** [comment]
Very good .

**Comment by DevStarKKK** [comment]
Thank you.
